// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.19.1
// source: community/v1/media.proto

/* eslint-disable */
import { MediaAction } from './enums';

export const protobufPackage = 'community.v1';

export interface Media {
  url?: string | undefined;
  fileId?: string | undefined;
  action?: MediaAction | undefined;
}

export const COMMUNITY_V1_PACKAGE_NAME = 'community.v1';
