// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.19.1
// source: community/v1/messages.proto

/* eslint-disable */
import { CommunityInfoCount } from "./counts";
import {
  CommunityMemberStatus,
  CommunityModeratorRole,
  CommunityModeratorStatus,
  CommunityStatus,
  CommunityVisibility,
} from "./enums";
import { Media } from "./media";
import { CommunityRule } from "./rules";

export const protobufPackage = "community.v1";

export interface Cursor {
  createdAt?: string | undefined;
  id?: string | undefined;
}

export interface CommunitySummary {
  id?: string | undefined;
  name?: string | undefined;
  title?: string | undefined;
  icon?: Media | undefined;
  banner?: Media | undefined;
  counts?: CommunityInfoCount | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
}

export interface Community {
  id?: string | undefined;
  name?: string | undefined;
  title?: string | undefined;
  description?: string | undefined;
  ownerId?: string | undefined;
  visibility?: CommunityVisibility | undefined;
  status?: CommunityStatus | undefined;
  icon?: Media | undefined;
  banner?: Media | undefined;
  rules?: CommunityRule[] | undefined;
  counts?: CommunityInfoCount | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  moderators?: Moderator[] | undefined;
}

export interface Moderator {
  id?: string | undefined;
  userId?: string | undefined;
  communityId?: string | undefined;
  invitedAt?: string | undefined;
  respondedAt?: string | undefined;
  role?: CommunityModeratorRole | undefined;
  status?: CommunityModeratorStatus | undefined;
}

export interface CommunityPage {
  community?: Community | undefined;
  viewerContext?: ViewerContext | undefined;
}

export interface ViewerContext {
  isMember?: boolean | undefined;
  isModerator?: boolean | undefined;
  moderatorRole?: CommunityModeratorRole | undefined;
}

export interface CommunityResponse {
  community?: Community | undefined;
}

export interface DeleteCommunityResponse {
  success?: boolean | undefined;
}

export interface CommunityMembershipResponse {
  exists?: boolean | undefined;
  communityId?: string | undefined;
  userId?: string | undefined;
  id?: string | undefined;
  status?: CommunityMemberStatus | undefined;
  joinedAt?: string | undefined;
  leftAt?: string | undefined;
  bannedAt?: string | undefined;
}

export interface JoinCommunityResponse {
  success?: boolean | undefined;
}

export const COMMUNITY_V1_PACKAGE_NAME = "community.v1";
