// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.19.1
// source: community/v1/queries.proto

import { CommunitySummary, Cursor } from './messages';

export const protobufPackage = 'community.v1';

export interface GetAllCommunitiesRequest {
  limit?: number | undefined;
  cursor?: Cursor | undefined;
}

export interface GetAllCommunitiesResponse {
  communities?: CommunitySummary[] | undefined;
  nextCursor?: Cursor | undefined;
}

export const COMMUNITY_V1_PACKAGE_NAME = 'community.v1';
