// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v3.19.1
// source: community/v1/requests.proto

/* eslint-disable */
import { CommunityVisibility } from './enums';
import { Media } from './media';

export const protobufPackage = 'community.v1';

export interface CreateCommunityRequest {
  name?: string | undefined;
  title?: string | undefined;
  description?: string | undefined;
  visibility?: CommunityVisibility | undefined;
  icon?: Media | undefined;
  banner?: Media | undefined;
  ownerId?: string | undefined;
}

export interface UpdateCommunityRequest {
  communityId?: string | undefined;
  title?: string | undefined;
  description?: string | undefined;
  visibility?: CommunityVisibility | undefined;
  icon?: Media | undefined;
  banner?: Media | undefined;
}

export interface DeleteCommunityRequest {
  communityId?: string | undefined;
}

export interface CommunityInfoRequest {
  communityName?: string | undefined;
  userId?: string | undefined;
}

export interface CommunityMembershipRequest {
  communityId?: string | undefined;
  userId?: string | undefined;
}

export const COMMUNITY_V1_PACKAGE_NAME = 'community.v1';
